#!/bin/sh

if [ $# -ne 3 ]; then
    echo "Usage: $(basename "$0") <old-email> <new-email> <new-name>"

    exit
fi

read -p "Old email: $1, new email: $2, new name: $3. Continue? y/N: " answer

if [ "X$answer" != "Xy" ]; then
    echo "Not continuing."

    exit
fi

read -p "Are you sure?? This is a descructive operation. y/N: " answer

if [ "X$answer" != "Xy" ]; then
    echo "Not continuing."

    exit
fi

FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch -f --env-filter '

OLD_EMAIL="'"$1"'"
CORRECT_EMAIL="'"$2"'"
CORRECT_NAME="'"$3"'"

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
