#!/bin/zsh

if [ $# -eq 1 ] && [ "$1" = "-e" ]; then curl icanhazip.com
elif [ $# -gt 0 ]; then echo Usage: $(basename "$0") [-e]; exit
else ifconfig | grep -E 'netmask.*broadcast' | grep -Eo '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*' | head -1; fi
