#!/bin/zsh

if [ $# -eq 1 ] && [ "$1" = "-p" ]; then
	curl -s https://api.my-ip.io/ip
elif [ $# -gt 0 ]; then
	echo Usage: $(basename "$0") [-p]; exit
else
	ifconfig | grep -E 'netmask.*broadcast' | grep -Eo '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*' | head -1
fi
