#!/bin/zsh

declare path="$1"

if [ ! -e "$path" ]; then
    path="$(launchctl-search "$path")"
fi

if [ -e "$path" ]; then
    launchctl unload -w "$path"; launchctl load -w "$path"
else
    exit -1
fi
