#!/bin/zsh

declare service="$1"

if [ ! -e "$service" ]; then
    service="$(launchctl-search "$service")"
fi

if [ -e "$service" ]; then
    launchctl unload -w "$service"; launchctl load -w "$service"
else
    exit -1
fi
