#!/bin/zsh

declare service="$1"

if [ ! -e "$service" ]; then
    service="$(launchctl-search "$service")"
fi

if [ -e "$service" ]; then
    launchctl unload -w "$service"
else
    echo Service $1 not found

    exit -1
fi
