#!/bin/zsh

local dir sizes parts
typeset -a sizes parts
sizes=(
  "drawable-land-hdpi/splash.png 800 480"
  "drawable-land-mdpi/splash.png 480 320"
  "drawable-land-xhdpi/splash.png 1280 720"
  "drawable-land-xxhdpi/splash.png 1600 960"
  "drawable-land-xxxhdpi/splash.png 1920 1280"
  "drawable-port-hdpi/splash.png 480 800"
  "drawable-port-mdpi/splash.png 320 480"
  "drawable-port-xhdpi/splash.png 720 1280"
  "drawable-port-xxhdpi/splash.png 960 1600"
  "drawable-port-xxxhdpi/splash.png 1280 1920"
  "drawable/splash.png 480 320"
)

dir="."

for i ("$sizes[@]"); do
	parts=("${(@s/ /)i}")

  mkdir -p "$dir/$(dirname $parts[1])"

  size="$parts[2]x$parts[3]"

  if [ $parts[2] -gt $parts[3] ] && [ -e "$1-landscape.png" ]; then
    magick "$1-landscape.png" -adaptive-resize "$size^" -gravity Center -extent "$size" "PNG32:$dir/$parts[1]"
  elif [ $parts[2] -lt $parts[3] ] && [ -e "$1-portrait.png" ]; then
    magick "$1-portrait.png" -adaptive-resize "$size^" -gravity Center -extent "$size" "PNG32:$dir/$parts[1]"
  elif [ -e "$1" ]; then
    magick "$1" -adaptive-resize "$size^" -gravity Center -extent "$size" "PNG32:$dir/$parts[1]"
  else
    echo "$1: not found"
  fi
done
