#!/bin/zsh

if [ $# -lt 1 ]; then
	echo "Please pass a value to encode in the QR code"

	exit
fi

declare tmp="$TMPDIR$(basename "$0")-$(uuidgen)"
trap "rm -rf '$tmp';" EXIT
mkdir -p "$tmp"

declare temp_file="$tmp/temp.svg"
declare text="$@"
declare output="${${text##*/}:0:30}"

npx qrcode-svg --ecl L --join --padding 0 --no-prettify "$text" > "$temp_file"
inkscape "$temp_file" -o "$output.pdf"
