#!/bin/zsh

if [ $# -lt 1 ]; then
	echo "Please pass a value to encode in the QR code"

	exit
fi

declare temp="$TMPDIR/encode-svg-temp.svg"
declare text="$@"
declare output="${text##*/}"

if [[ $text == *bible.com* ]]; then
	# Set to lowercase
	text="${text:l}"
	output="${output:l}"

	# Remove protocol
	text="${text#*://}"

	# Remove www, if present
	text="${text#www.}"

	# Remove "my", if present
	text="${text#my.}"

	# Remove "bible/", if present
	text="${text/bible\//}"

	# Remove the version at the end (the number in the URL already defines the version)
	text="${text%.[a-zA-Z]?(?|??|???)}"
fi

npx qrcode-svg --ecl L --join --padding 0 --no-prettify "$text" > "$temp"
inkscape "$temp" -o "$output.pdf"
rm "$temp"
