#!/bin/zsh

if [ $# -lt 1 ]; then
	echo "Please pass a value to encode in the QR code"

	exit
fi

declare tmp="$TMPDIR$(basename "$0")-$(uuidgen)"
trap "rm -rf '$tmp';" EXIT
mkdir -p "$tmp"

declare temp_file="$tmp/temp.svg"
declare output="${${text##*/}:0:30}"

if [ "$1" = "-o" ] || [ "$1" = "--out" ]; then
	output="$2"

	shift
	shift
fi

declare text="$@"

# For error correction level: L, M, Q, H
npx qrcode-svg --ecl L --join --padding 0 --no-prettify "$text" > "$temp_file"
inkscape "$temp_file" -o "$output.pdf"
