#!/bin/zsh

if [ $# -eq 0 ]; then
	echo "Usage: $(basename "$0") <input-file...>"
fi

declare tmp="$TMPDIR$(basename "$0")-$(uuidgen)"
trap "rm -rf '$tmp';" EXIT
mkdir -p "$tmp"

while [ $# -gt 0 ]; do
	declare file="$1"
	declare name="${${file##*/}%%.*}"
	declare temp1="$tmp/${name}1.svg"
	declare temp2="$tmp/${name}2.svg"

	if [ "${file%%.*}" = "svg" ]; then
		cp "$file" "$temp1"
	else
		inkscape "$file" -o "$temp1"
	fi

	npx svgo "$temp1" -q -o "$temp2"
	inkscape "$temp2" -o "$name.pdf"

	shift
done
