#!/bin/zsh

if [ $# -eq 0 ]; then
	echo "Usage: $(basename "$0") <input-file...>"
fi

declare tmp="$TMPDIR$(basename "$0")-$(uuidgen)"
trap "rm -rf '$tmp';" EXIT
mkdir -p "$tmp"

while [ $# -gt 0 ]; do
	declare file="$1"
	declare name="${${file##*/}%%.*}"
	declare temp="$tmp/$name.svg"

	inkscape "$file" -o "$temp"
	npx svgo "$temp" -q -o "$name.svg"

	shift
done
